os: osx
language: csharp
solution: ./JsonButlerIde/JsonButlerIde.sln
dotnet: 2.2.104
python: 3.7
mono: latest
env:
  global:
    - LULLAPY_ROOT=$TRAVIS_BUILD_DIR/lullapy
    - VSIX_BIN=./JsonButlerIde/JsonButlerIde/bin
    - VSIX_NAME=JsonButlerIde
  matrix:
    - CONFIG_NAME=Release
    - CONFIG_NAME=Debug
before_install:
  - export PYTHONPATH=$LULLAPY_ROOT:$PYTHONPATH
  - chmod -R a+x $LULLAPY_ROOT
script:
  - python3 -m andeart.lullapy.netrestore -s "$TRAVIS_SOLUTION"
  - python3 -m andeart.lullapy.netbuild -s "$TRAVIS_SOLUTION" -c "$CONFIG_NAME"
  - python3 -m andeart.lullapy.nettest -t "$TESTS_BIN/$CONFIG_NAME/$TESTS_ASSEMBLY"
  - python3 -m andeart.lullapy.plainexist -f "$VSIX_BIN/$CONFIG_NAME/$VSIX_NAME.vsix;$VSIX_BIN/$CONFIG_NAME/$VSIX_NAME.pkgdef"